--- 
maven-build: 
  scrpit: 
    - "mvn build -B"
  stage: build
maven-package: 
  script: 
    - "mvn package -B"
  stage: package
stages: "-test -build -package"
unit_test: 
  script: 
    - "mvn clean test -B"
  stage: test