version: '2'
services:
  eureka:
    image: eureka
    restart: always
    build: ./eureka-server
    container_name: eureka
    ports:
      - 8090:8090

  config:
     image: config
     restart: always
     build: ./Config-server
     container_name: config
     ports:
       - 8888:8888

  api-gateway:
    environment:
      REGISTRY_URL: eureka
    build: ./Api-Gateway
    container_name: api-gateway
    image: api
    ports:
      - 8020:8020
    depends_on:
      - eureka
      - config
      

  redis: 
    container_name: redis
    image: redis
    expose:
      - 6379
    ports: 
      - "6379:6379"
      
  kafka:
    environment:
     ADVERTISED_HOST: 10.20.1.196
     ADVERTISED_PORT: 9092
    image: spotify/kafka
    container_name: kafka
    restart: always
    ports: 
     - 2181:2181
     - 9092:9092
    expose:
     - 9092

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    expose:
     - 27017
    ports:
     - 27017:27017

  persistence:
    build: ./persistence-manager
    container_name: persistence
    image: persistence
    ports:
      - 8055:8055
    depends_on:
      - kafka
      - mongodb
      - eureka
      - config
      

  cassandra_db1: 
    container_name: cassandra_db1
    image: cassandra
    restart: always
    expose:
      - "9042"
    ports: 
      - "9042:9042"  

  reporting-service:     
    build: ./ReportingService
    container_name: reporting-service
    image: reporting-service
    depends_on: 
      - kafka
      - eureka
      - cassandra_db1
      - config
    links:
      - cassandra_db1
    ports: 
      - "8040:8040"
    environment:
      CASSANDRA_HOST: cassandra_db1

  auth_sql:
    environment:
      MYSQL_ROOT_USERNAME: news123
      MYSQL_ROOT_PASSWORD: 9396344037
      MYSQL_DATABASE: user
    image: mysql
    restart: always
    ports:
      - 3308:3306

  auth-service:
    build: ./Authentication_server
    container_name: auth-service
    image: auth-service
    expose:
      - 8087
    ports:
      - 8087:8087
    depends_on:
      - eureka
      - config

  user-persistence:
    build: ./user-persistence
    container_name: user-persistence
    image: user_persistence
    ports:
      - 8088:8088
    expose:
      - 8088
    depends_on:
      - eureka
      - config
      

  job-manager:
    build: ./JobManager
    container_name: job-manager
    image: job-manager
    ports:
      - 8021:8021
    depends_on:
      - eureka
      - kafka
      - config
      

  job-scheduler: 
    build: ./Engine_dw-job-scheduler
    container_name: job-scheduler
    depends_on: 
      - kafka
      - eureka
      - redis
      - config
    links:
      - redis
    image: job-scheduler
    ports: 
      - "8060:8060"
    restart: always

  results-processor: 
    build: ./Engine_dw-results-processor
    container_name: results-processor
    depends_on: 
      - kafka
      - redis
      - eureka
      - config
    links:
      - redis
    image: results-processor
    ports:
      - "8065:8065"
    restart: always

  state-initializer: 
    build: ./Engine_dw-state-initializer
    container_name: state-initializer
    depends_on: 
      - kafka
      - eureka
      - redis
      - config
    links:
      - redis
    image: state-initializer
    ports: 
      - "8078:8078"
    restart: always

  task-scheduler: 
    build: ./Engine_dw-task-scheduler
    container_name: task-scheduler
    depends_on: 
      - kafka
      - eureka
      - config
    image: task-scheduler
    ports: 
      - "7687:7687"

  socket-service:
    build: ./SocketService
    container_name: socket-service
    depends_on:
      - eureka
      - kafka
      - config
    image: socket-service
    ports:
      - "9000:9000"
